### ISSUE TITLE
Static plugin directory

### ISSUE THREAD

**Issue by denisdulici** [joomlaworks/fill-it-up-for-wordpress#1]
First of all, congrats and thanks for such a nice plugin.

I can see that in most of cases you've assumed that the plugin directory will be static as **fillitup**. However, that will fail as some WP users change and/or WordPress itself changes if the installation fails.

Instead of that, the [plugin_dir_path](https://developer.wordpress.org/reference/functions/plugin_dir_path/#comment-1113) function is recommended.

Regards.

**Comment by fevangelou** [comment]
Thank you Denis!

Resolved here: https://github.com/joomlaworks/fill-it-up-for-wordpress/commit/75ee6031ee9b23bbbedc5db9738abdff9d39db99
